apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
      app: mariadb-front
  template:
    metadata:
      labels:
        app: nginx
        app: mariadb-front
    spec:

      volumes:
      - name: bdd-front-volume
        persistentVolumeClaim:
          claimName: bdd-front-pvc

      - name: nginx-volume
        persistentVolumeClaim:
          claimName: nginx-pvc


      containers:
      - name: mariadb-front
        image: beefr/mariadb-qcm:latest
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: pwd
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: bdd-front-volume

      - name: nginx
        image: frontend:latest
        imagePullPolicy: Never
        ports:
        - name: front-port
          containerPort: 8080
        volumeMounts:
        - mountPath: /app/OnePiece
          name: nginx-volume

