apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer 
  selector:
    app: nginx
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort 
  selector:
    app: nginx
  ports:
    - name: tcp-mysql-front
      port: 3306
      targetPort: 3306
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb-front
  name: mariadb-front

spec:
  type: ClusterIP
  selector: 
    app: mariadb-front
  ports:
  - name: tcp-mysql-front
    port: 3306
    protocol: TCP
    targetPort: 3306


