apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort 
  selector:
    app: nginx
  ports:
    - name: front-port
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30036
    - name: front-back-port
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30037
    - name: tcp-mysql-front
      port: 3306
      targetPort: 3306
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb-front
  name: mariadb-front

spec:
  type: ClusterIP
  selector: 
    app: mariadb-front
  ports:
  - name: tcp-mysql-front
    port: 3306
    protocol: TCP
    targetPort: 3306


