apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anog-pvc
  labels:
    name: anog-pvc
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
