apiVersion: v1
kind: Service
metadata:
  name: anog
  labels:
    app: anog
spec:
  type: NodePort 
  selector:
    app: anog
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
    name: http

  - protocol: TCP
    port: 3306
    targetPort: 3306
    name: tcp-mysql-back

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb-anog
  name: mariadb-anog

spec:
  type: ClusterIP
  selector: 
    app: mariadb-anog
  ports:
  - name: tcp-mysql-back
    port: 3306
    protocol: TCP
    targetPort: 3306


